apiVersion: v1
kind: Pod

metadata:
  name: pod-example-nginx
  labels:
    app: myapp
    tier: lb
  
spec:
  containers:
    - name: nginx-container
      image: nginx

  nodeSelector:
    type: worker1
