apiVersion: v1
kind: Pod

metadata:
  name: pod-w-affinity
  labels:
    type: test-nodeaffinity

spec:

   containers:
   - name: data-processor
     image: data-processor



   affinity:
     nodeAffinity:

       # type of Node affinity 
       # required, preferred, ignored 
       requiredDuringSchedulingIgnoredDuringExecution:  
         nodeSelectorTerms:
         - matchExpressions:
           - key: size
             operator: In
             values:
             - Large
             - Medium

# LARGE OR MEDIUM

# NODE AFFINITY: 
 
# During Scheduling -> state where  pod was not created yet, is being created for the first time
# During Execution ->  pod is running but there was a change made on the env that affects node affinity of a pod. E g node changing labels

# Required During Scheduling requires that the pod must be created within that node with the given affiity rules 
# if pod affinity does not match any node label, the pod is not created

# Prefered During Scheduling will tell the scheduler to put the pod undeer the preferred node with the matching labels, but if it does not find it, it just puts it on a
# available node

# Ignored During Execution will tell the scheduler to keep the pods up and running even if node affinity properties are changed





 

 

