apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: example-replicaset
  labels:
    app: example-app
    type: back-end
spec:
  template:

     metadata:
       name: nginx-example-pod
       labels:
         app: example-app
         type: back-end
    
     spec:
       containers:
       - name: nginx
         image: nginx

  replicas: 4
  selector:
       matchLabels: 
         app: example-app
         type: back-end
