apiVersion: v1
kind: ReplicationController
metadata:
  name: example-rc
  labels:
    app: example-app
    type: back-end
spec:
  template:

     metadata:
       name: redis-example-pod
       labels:
         app: example-app
         type: back-end
    
     spec:
       containers:
       - name: redis-example-container
         image: redis

  replicas: 4
