apiVersion: v1
kind: Service

metadata:
  name: example-service-nginx-np-deploymnet

spec:
  type: NodePort
  ports:
  - targetPort: 80 
    port: 8080
    nodePort: 30009
  selector:
    app: example-app
    type: example-service-to-deployment



# targetPort: pod port where we want to forward traffic to
# port: service port
# nodePort: node port
# links tod deployments resources via selector 
